# api_platform:
#     mapping:
#         paths: ['%kernel.project_dir%/src/Entity']
#     formats:  
#         json: ['application/json']
#         json: ['application/json', 'application/ld+json'] 
#     title: Hello API Platform
#     version: 1.0.0
#     defaults:
#         stateless: true
#         cache_headers:
#             vary: ['Content-Type', 'Authorization', 'Origin']
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:  
        jsonld: ['application/json', 'application/ld+json'] 
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
