lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    # pass_phrase: '%env(JWT_PASSPHRASE)%'
    pass_phrase: 'hack2025'
    token_ttl: 3600  # Durée de validité du token (1 heure)

